DefaultContentLanguage: en
languageCode: "en-us"

title: "ICON Community"
description: "ICON Community"

theme:
  - icon-community-v1

permalinks:
  post: :slug/
  page: :slug/

categories:
  - announcements
  - community
  - ecosystem
  - events
  - opinion
  - technology
  - tutorial

params:
  banner:
    message: Our 200M ICX Interoperability Incentive Program is live.
    url: /interoperability-incentive-program/
  featured_post_url: what-is-the-icx-token
  social:
    discord_url: https://discord.gg/BvWzx9nZgv
    github_url: https://github.com/icon-project
    newsletter_url: https://www.getrevue.co/profile/helloiconworld
    roadmap_url: https://iconfoundation.notion.site/ICON-2-0-Roadmap-064c2ee577714c58b487a76c7f3998ff
    twitter_url: https://twitter.com/helloiconworld
  forms:
    faq_submission_url: https://discord.gg/gMCCdbjVf9
    ecosystem_submission_url: https://se8br1ugut6.typeform.com/to/MBBDnTNG
    incentive_program_submission_url: 