DefaultContentLanguage: en
languageCode: "en-us"

title: "ICON Community"
description: "ICON Community"

theme:
  - icon-community-v1

permalinks:
  posts: :slug/
  pages: :slug/

categories:
  - announcements
  - community
  - ecosystem
  - events
  - opinion
  - technology
  - tutorial

params:
  featured_post_url: what-is-the-icx-token
  dapps:
    balanced_url: https://balanced.network
    omm_url: https://omm.finance
    optimus_url: https://optimus.finance
    cps_url: https://cps.icon.community
  social:
    discord_url: https://discord.gg/gMCCdbjVf9
    github_url: https://github.com/icon-project
    twitter_url: https://twitter.com/helloiconworld
  forms:
    faq_submission_url: https://discord.gg/gMCCdbjVf9
