DefaultContentLanguage: en
languageCode: "en-us"

title: "ICON Community"
description: "ICON Community"

theme:
  - icon-community-v1

permalinks:
  posts: :slug/
  pages: :slug/

categories:
  - announcements
  - community
  - ecosystem
  - events
  - opinion
  - technology
  - tutorial

params:
  banner:
    message: Our 200M ICX Interoperability Incentive Program is live.
    url: /incentive-program/
  featured_post_url: what-is-the-icx-token
  social:
    discord_url: https://discord.gg/gMCCdbjVf9
    github_url: https://github.com/icon-project
    twitter_url: https://twitter.com/helloiconworld
  forms:
    faq_submission_url: https://discord.gg/gMCCdbjVf9
