DefaultContentLanguage: en
languageCode: "en-us"
canonifyURLs: true
baseURL: https://icon.community/

title: "ICON Community"
description: "ICON Community"

theme:
  - icon-community-v1

permalinks:
  post: :slug/
  page: :slug/

categories:
  - announcements
  - community
  - ecosystem
  - events
  - opinion
  - technology
  - tutorial

params:
  banner:
    message: Read the BTP Litepaper to learn about ICON's bridging solution!
    url: /assets/btp-litepaper.pdf
  featuredPostUrl: what-is-the-icx-token
  social:
    discordUrl: https://discord.com/invite/7a75Hf3cFm
    githubUrl: https://github.com/icon-project
    newsletterUrl: https://foundation.us15.list-manage.com/subscribe?u=d8b1e5594bd92c54dc0c7141c&id=fbc02bbf32
    roadmapUrl: https://iconfoundation.notion.site/BTP-Integration-Milestones-1f1decaab3d246f5a042ff45a21aab86
    twitterUrl: https://twitter.com/helloiconworld
  forms:
    faqSubmissionUrl: https://discord.com/invite/7a75Hf3cFm
    ecosystemSubmissionUrl: https://se8br1ugut6.typeform.com/to/MBBDnTNG
    incentiveProgramSubmissionUrl: https://se8br1ugut6.typeform.com/to/Qkialcom

markup:
  tableOfContents:
    endLevel: 2