DefaultContentLanguage: en
languageCode: "en-us"
canonifyURLs: true
baseURL: https://icon.community/

title: "ICON Community"
description: "ICON is a public blockchain protocol building a hyperconnected future with BTP, a chain-agnostic interoperability solution."

permalinks:
  post: :slug/
  page: :slug/

categories:
  - announcements
  - community
  - ecosystem
  - events
  - opinion
  - technology
  - tutorial

params:
  authors:
    espanicon:
      name: "Espanicon"
      description: "Espanicon is an ICON validator. Their goal is to participate in the chain governance of the network and expand the ICON ecosystem by building projects in it and collaborating with other validators."
      validatorAddress: "hx9fa9d224306b0722099d30471b3c2306421aead7"
    icon-foundation:
      name: "ICON Foundation"
      description:
    rhizome:
      name: "RHIZOME"
      description:
      validatorAddress: "hx4a43790d44b07909d20fbcc233548fc80f7a4067"
  banner:
    message:
    url:
  featuredPostUrl: what-is-the-icx-token
  forms:
    faqSubmissionUrl: https://discord.com/invite/7a75Hf3cFm
    ecosystemSubmissionUrl: https://se8br1ugut6.typeform.com/to/MBBDnTNG
    incentiveProgramSubmissionUrl: https://se8br1ugut6.typeform.com/to/Qkialcom
  social:
    discordUrl: https://discord.com/invite/7a75Hf3cFm
    githubUrl: https://github.com/icon-project
    newsletterUrl: https://foundation.us15.list-manage.com/subscribe?u=d8b1e5594bd92c54dc0c7141c&id=fbc02bbf32
    roadmapUrl: https://iconfoundation.notion.site/BTP-Integration-Milestones-1f1decaab3d246f5a042ff45a21aab86
    twitterUrl: https://twitter.com/helloiconworld
  
markup:
  tableOfContents:
    endLevel: 2