DefaultContentLanguage: en
languageCode: "en-us"

title: "ICON Community"
description: "ICON Community"

theme:
  - icon-community-v1

permalinks:
  posts: :slug/
  pages: :slug/

params:
  social:
    discord_url: https://discord.gg/gMCCdbjVf9
    github_url: https://github.com/icon-project
    twitter_url: https://twitter.com/helloiconworld
  forms:
    faq_submission_url: https://discord.gg/gMCCdbjVf9
